### ISSUE TITLE
Hydra build failed 

### ISSUE THREAD

**Issue by purepani** [DavHau/dreampkgs#26]
I just noticed that the hydra build for the most recent commit has failed. It looks like it didn't detect any input changes from the commit, which is likely why it failed.

**Comment by Mic92** [comment]
Is this not build by buildbot now?

**Comment by purepani** [comment]
It looks like @DavHau implied it is in https://github.com/nix-community/dream2nix/issues/741, and it looks like it's building at buildbot.nix-community.org. However, there's no reference to it anywhere in the readme, which only references hydra, so that should probably be updated.
